# Generated by Django 4.2.25 on 2026-04-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_invoice_options_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='goods_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Goods'), ('SPECIAL', 'Special Goods')], default='NORMAL', max_length=10),
        ),
    ]
